services:
  db:
    image: postgres:15
    container_name: postgres_django
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build: .
    container_name: django_web
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=Lince.settings
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:


networks:
  django_network:
    driver: bridge
